version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:16
    container_name: finance_postgres
    restart: always
    environment:
      - POSTGRESQL_DATABASE=finance_db
      - POSTGRESQL_USERNAME=finance_user
      - POSTGRESQL_PASSWORD=finance_pass
    ports:
      - "5432:5432"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: finance_zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: finance_kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
