// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                 uuid.UUID
	Code               string
	Name               string
	Type               string
	ParentID           uuid.NullUUID
	Status             string
	AllowManualJournal sql.NullBool
	CreatedAt          sql.NullTime
	CreatedBy          sql.NullString
	UpdatedAt          sql.NullTime
	UpdatedBy          sql.NullString
	Revision           sql.NullInt32
}

type Accrual struct {
	ID          uuid.UUID
	Description sql.NullString
	Amount      string
	AccrualDate time.Time
	AccountID   string
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedAt   sql.NullTime
	UpdatedBy   sql.NullString
	Revision    sql.NullInt32
}

type AccrualExternalRef struct {
	ID        uuid.UUID
	AccrualID uuid.UUID
	System    string
	RefID     string
	CreatedAt sql.NullTime
}

type AllocationRule struct {
	ID                  uuid.UUID
	Name                string
	Basis               string
	SourceAccountID     string
	TargetCostCenterIds []string
	Formula             sql.NullString
	CreatedAt           sql.NullTime
	CreatedBy           sql.NullString
	UpdatedAt           sql.NullTime
	UpdatedBy           sql.NullString
	Revision            sql.NullInt32
}

type AuditEvent struct {
	ID           uuid.UUID
	UserID       string
	Action       string
	Timestamp    time.Time
	Details      sql.NullString
	ResourceType sql.NullString
	ResourceID   sql.NullString
	CreatedAt    sql.NullTime
}

type AuditField struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	CreatedBy sql.NullString
	UpdatedAt sql.NullTime
	UpdatedBy sql.NullString
	Revision  sql.NullString
}

type BalanceSheetReport struct {
	ID               uuid.UUID
	OrganizationID   string
	PeriodStart      time.Time
	PeriodEnd        time.Time
	TotalAssets      string
	TotalLiabilities string
	NetWorth         string
	CreatedAt        sql.NullTime
	CreatedBy        sql.NullString
	UpdatedAt        sql.NullTime
	UpdatedBy        sql.NullString
	Revision         sql.NullInt32
}

type BankAccount struct {
	ID              uuid.UUID
	Name            string
	AccountNumber   string
	IfscOrSwift     string
	LedgerAccountID sql.NullString
	CreatedAt       sql.NullTime
	CreatedBy       sql.NullString
	UpdatedAt       sql.NullTime
	UpdatedBy       sql.NullString
	Revision        sql.NullInt32
}

type BankTransaction struct {
	ID                   uuid.UUID
	BankAccountID        uuid.UUID
	Amount               string
	TransactionDate      time.Time
	Description          sql.NullString
	Reference            sql.NullString
	Reconciled           sql.NullBool
	MatchedReferenceType sql.NullString
	MatchedReferenceID   uuid.NullUUID
	CreatedAt            sql.NullTime
	CreatedBy            sql.NullString
	UpdatedAt            sql.NullTime
	UpdatedBy            sql.NullString
	Revision             sql.NullInt32
}

type Budget struct {
	ID          uuid.UUID
	Name        string
	TotalAmount string
	Status      string
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedAt   sql.NullTime
	UpdatedBy   sql.NullString
	Revision    sql.NullInt32
}

type BudgetAllocation struct {
	ID              uuid.UUID
	BudgetID        uuid.UUID
	DepartmentID    string
	AllocatedAmount string
	SpentAmount     sql.NullString
	RemainingAmount sql.NullString
	CreatedAt       sql.NullTime
	CreatedBy       sql.NullString
	UpdatedAt       sql.NullTime
	UpdatedBy       sql.NullString
	Revision        sql.NullInt32
}

type BudgetAllocationExternalRef struct {
	ID           uuid.UUID
	AllocationID uuid.UUID
	System       string
	RefID        string
	CreatedAt    sql.NullTime
}

type BudgetExternalRef struct {
	ID        uuid.UUID
	BudgetID  uuid.UUID
	System    string
	RefID     string
	CreatedAt sql.NullTime
}

type CashFlowForecast struct {
	ID              uuid.UUID
	OrganizationID  string
	PeriodStart     time.Time
	PeriodEnd       time.Time
	ForecastDetails string
	CreatedAt       sql.NullTime
	CreatedBy       sql.NullString
	UpdatedAt       sql.NullTime
	UpdatedBy       sql.NullString
	Revision        sql.NullInt32
}

type ComplianceReport struct {
	ID             uuid.UUID
	OrganizationID string
	PeriodStart    time.Time
	PeriodEnd      time.Time
	Jurisdiction   string
	Details        string
	CreatedAt      sql.NullTime
	CreatedBy      sql.NullString
	UpdatedAt      sql.NullTime
	UpdatedBy      sql.NullString
	Revision       sql.NullInt32
}

type Consolidation struct {
	ID          uuid.UUID
	EntityIds   []string
	PeriodStart time.Time
	PeriodEnd   time.Time
	Report      string
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedAt   sql.NullTime
	UpdatedBy   sql.NullString
	Revision    sql.NullInt32
}

type CostAllocation struct {
	ID            uuid.UUID
	CostCenterID  uuid.UUID
	Amount        string
	ReferenceType string
	ReferenceID   string
	CreatedAt     sql.NullTime
	CreatedBy     sql.NullString
	UpdatedAt     sql.NullTime
	UpdatedBy     sql.NullString
	Revision      sql.NullInt32
}

type CostCenter struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedAt   sql.NullTime
	UpdatedBy   sql.NullString
	Revision    sql.NullInt32
}

type CreditDebitNote struct {
	ID        uuid.UUID
	InvoiceID uuid.UUID
	Type      string
	Amount    string
	Reason    sql.NullString
	CreatedAt sql.NullTime
	CreatedBy sql.NullString
	UpdatedAt sql.NullTime
	UpdatedBy sql.NullString
	Revision  sql.NullInt32
}

type CreditDebitNoteExternalRef struct {
	ID        uuid.UUID
	NoteID    uuid.UUID
	System    string
	RefID     string
	CreatedAt sql.NullTime
}

type ExchangeRate struct {
	ID            uuid.UUID
	BaseCurrency  string
	QuoteCurrency string
	Rate          string
	AsOf          time.Time
	CreatedAt     sql.NullTime
	CreatedBy     sql.NullString
	UpdatedAt     sql.NullTime
	UpdatedBy     sql.NullString
	Revision      sql.NullString
}

type Expense struct {
	ID           uuid.UUID
	Category     string
	Amount       string
	ExpenseDate  time.Time
	CostCenterID uuid.NullUUID
	CreatedAt    sql.NullTime
	CreatedBy    sql.NullString
	UpdatedAt    sql.NullTime
	UpdatedBy    sql.NullString
	Revision     sql.NullInt32
}

type ExpenseExternalRef struct {
	ID        uuid.UUID
	ExpenseID uuid.UUID
	System    string
	RefID     string
	CreatedAt sql.NullTime
}

type ExternalRef struct {
	ID        uuid.UUID
	System    string
	RefID     string
	CreatedAt sql.NullTime
}

type FinanceInvoiceCreatedEvent struct {
	ID             uuid.UUID
	InvoiceID      uuid.UUID
	InvoiceNumber  string
	InvoiceDate    time.Time
	PartyRefID     uuid.NullUUID
	Total          string
	OrganizationID string
	CreatedAt      sql.NullTime
}

type FinancePaymentReceivedEvent struct {
	ID             uuid.UUID
	PaymentDueID   uuid.UUID
	InvoiceID      uuid.UUID
	AmountPaid     string
	PaidAt         time.Time
	Reference      sql.NullString
	OrganizationID string
	CreatedAt      sql.NullTime
}

type GstBreakup struct {
	ID            uuid.UUID
	InvoiceID     uuid.UUID
	TaxableAmount string
	Cgst          sql.NullString
	Sgst          sql.NullString
	Igst          sql.NullString
	TotalGst      sql.NullString
	CreatedAt     sql.NullTime
	CreatedBy     sql.NullString
	Revision      sql.NullInt32
}

type GstDocStatus struct {
	ID             uuid.UUID
	InvoiceID      uuid.UUID
	EinvoiceStatus sql.NullString
	Irn            sql.NullString
	AckNo          sql.NullString
	AckDate        sql.NullTime
	EwayStatus     sql.NullString
	EwayBillNo     sql.NullString
	EwayValidUpto  sql.NullTime
	LastError      sql.NullString
	LastSyncedAt   sql.NullTime
	CreatedAt      sql.NullTime
	CreatedBy      sql.NullString
	Revision       sql.NullInt32
}

type GstRegime struct {
	ID            uuid.UUID
	InvoiceID     uuid.UUID
	Gstin         string
	PlaceOfSupply string
	ReverseCharge sql.NullBool
	CreatedAt     sql.NullTime
	CreatedBy     sql.NullString
	Revision      sql.NullInt32
}

type InventoryCostPostedEvent struct {
	ID             uuid.UUID
	ReferenceType  string
	ReferenceID    uuid.UUID
	Amount         string
	CostCenterID   sql.NullString
	OrganizationID string
	CreatedAt      sql.NullTime
}

type Invoice struct {
	ID                   uuid.UUID
	InvoiceNumber        string
	Type                 string
	InvoiceDate          time.Time
	DueDate              sql.NullTime
	DeliveryDate         sql.NullTime
	PartyRefID           uuid.NullUUID
	OrganizationID       string
	PoNumber             sql.NullString
	EwayNumberLegacy     sql.NullString
	StatusNote           sql.NullString
	Status               string
	PaymentReference     sql.NullString
	ChallanNumber        sql.NullString
	ChallanDate          sql.NullTime
	LrNumber             sql.NullString
	TransporterName      sql.NullString
	TransporterID        sql.NullString
	VehicleNumber        sql.NullString
	AgainstInvoiceNumber sql.NullString
	AgainstInvoiceDate   sql.NullTime
	Subtotal             string
	GrandTotal           string
	GstRate              sql.NullString
	GstCgst              sql.NullString
	GstSgst              sql.NullString
	GstIgst              sql.NullString
	CreatedAt            sql.NullTime
	CreatedBy            sql.NullString
	UpdatedAt            sql.NullTime
	UpdatedBy            sql.NullString
	Revision             sql.NullInt32
}

type InvoiceDiscount struct {
	ID          uuid.UUID
	InvoiceID   uuid.UUID
	Description sql.NullString
	Amount      string
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	Revision    sql.NullInt32
}

type InvoiceItem struct {
	ID           uuid.UUID
	InvoiceID    uuid.UUID
	Name         string
	Description  sql.NullString
	Hsn          sql.NullString
	Quantity     int32
	UnitPrice    string
	LineSubtotal string
	LineTotal    string
	CostCenterID sql.NullString
	CreatedAt    sql.NullTime
	CreatedBy    sql.NullString
	UpdatedAt    sql.NullTime
	UpdatedBy    sql.NullString
	Revision     sql.NullInt32
}

type InvoiceItemDiscount struct {
	ID          uuid.UUID
	ItemID      uuid.UUID
	Description sql.NullString
	Amount      string
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	Revision    sql.NullInt32
}

type InvoiceItemTax struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	Name      string
	Rate      string
	Amount    string
	CreatedAt sql.NullTime
	CreatedBy sql.NullString
	Revision  sql.NullInt32
}

type InvoiceTax struct {
	ID        uuid.UUID
	InvoiceID uuid.UUID
	Name      string
	Rate      string
	Amount    string
	CreatedAt sql.NullTime
	CreatedBy sql.NullString
	Revision  sql.NullInt32
}

type JournalEntry struct {
	ID          uuid.UUID
	JournalDate time.Time
	Reference   sql.NullString
	Memo        sql.NullString
	SourceType  sql.NullString
	SourceID    sql.NullString
	CreatedAt   sql.NullTime
	CreatedBy   sql.NullString
	UpdatedAt   sql.NullTime
	UpdatedBy   sql.NullString
	Revision    sql.NullInt32
}

type JournalEntryExternalRef struct {
	ID        uuid.UUID
	EntryID   uuid.UUID
	System    string
	RefID     string
	CreatedAt sql.NullTime
}

type JournalLine struct {
	ID           uuid.UUID
	EntryID      uuid.UUID
	AccountID    uuid.UUID
	Side         string
	Amount       string
	CostCenterID sql.NullString
	Description  sql.NullString
	CreatedAt    sql.NullTime
}

type LedgerEntry struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Description     sql.NullString
	Side            string
	Amount          string
	TransactionDate time.Time
	CostCenterID    sql.NullString
	ReferenceType   sql.NullString
	ReferenceID     sql.NullString
	CreatedAt       sql.NullTime
	CreatedBy       sql.NullString
	UpdatedAt       sql.NullTime
	UpdatedBy       sql.NullString
	Revision        sql.NullInt32
}

type LedgerEntryExternalRef struct {
	ID            uuid.UUID
	LedgerEntryID uuid.UUID
	System        string
	RefID         string
	CreatedAt     sql.NullTime
}

type PartyRef struct {
	ID            uuid.UUID
	Kind          int16
	ExternalRefID uuid.NullUUID
	DisplayName   sql.NullString
	CreatedAt     sql.NullTime
}

type PaymentDue struct {
	ID        uuid.UUID
	InvoiceID uuid.UUID
	AmountDue string
	DueDate   time.Time
	Status    string
	CreatedAt sql.NullTime
	CreatedBy sql.NullString
	UpdatedAt sql.NullTime
	UpdatedBy sql.NullString
	Revision  sql.NullInt32
}

type PaymentDueExternalRef struct {
	ID           uuid.UUID
	PaymentDueID uuid.UUID
	System       string
	RefID        string
	CreatedAt    sql.NullTime
}

type PayrollPostedEvent struct {
	ID             uuid.UUID
	PayrollRunID   uuid.UUID
	TotalGross     string
	TotalNet       string
	RunDate        time.Time
	OrganizationID string
	CreatedAt      sql.NullTime
}

type ProfitLossReport struct {
	ID             uuid.UUID
	OrganizationID string
	PeriodStart    time.Time
	PeriodEnd      time.Time
	TotalRevenue   string
	TotalExpenses  string
	NetProfit      string
	CreatedAt      sql.NullTime
	CreatedBy      sql.NullString
	UpdatedAt      sql.NullTime
	UpdatedBy      sql.NullString
	Revision       sql.NullInt32
}

type RequestMetadatum struct {
	ID             uuid.UUID
	RequestID      string
	OrganizationID sql.NullString
	TenantID       sql.NullString
	AuthSubject    sql.NullString
	SourceSystem   sql.NullString
	TraceID        sql.NullString
	CreatedAt      sql.NullTime
}

type TrialBalanceEntry struct {
	ID            uuid.UUID
	ReportID      uuid.UUID
	LedgerAccount string
	Debit         string
	Credit        string
	CreatedAt     sql.NullTime
	CreatedBy     sql.NullString
}

type TrialBalanceReport struct {
	ID             uuid.UUID
	OrganizationID string
	PeriodStart    time.Time
	PeriodEnd      time.Time
	CreatedAt      sql.NullTime
	CreatedBy      sql.NullString
	UpdatedAt      sql.NullTime
	UpdatedBy      sql.NullString
	Revision       sql.NullInt32
}

type VendorBillApprovedEvent struct {
	ID             uuid.UUID
	VendorBillID   uuid.UUID
	Amount         string
	ApprovedAt     time.Time
	OrganizationID string
	CreatedAt      sql.NullTime
}
